trigger:
  - main
  - Sprint5

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm run build:dev
    displayName: 'Build Angular Application with development environment'
    
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'dist/ProvaTeste/browser'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: AzureStaticWebApp@0
    inputs:
      cwd: '$(Build.ArtifactStagingDirectory)'
      app_location: '/'
      skip_app_build: true
      skip_api_build: true
      verbose: true
    env:
      azure_static_web_apps_api_token: '$(azure_static_web_apps_api_token)'
